### ISSUE TITLE
[feature idea] PUBSUB updates as a channel

### ISSUE THREAD

**Issue by dvirsky** [garyburd/redigo#113]
It would be nice to have PUBSUB connections spawn a function that reads their updates, and pushes them down a channel. 

Besides being "more idiomatic" (god I hate this term :) ), it will give me the advantage of being able to `select` on the incoming pubsub channel alongside a timeout or cancellation channel.

**Comment by garyburd** [comment]
Implement the goroutine in your application. The basic for loop is six lines of code.

A robust application will want to handle some or all of the following:

- Reconnect with backfill.
- Error handling.
- Goroutine termination.

The complexity of an API that provides these features is not worth the small number lines of code that it will save the application developer. 

Although it's somewhat common to provide APIs that wrap blocking operations with a goroutine, it's not necessarily best practice. It's not an approach used in the standard packages.

**Comment by dvirsky** [comment]
Fair enough, although to have an API that does all you've mentioned will be much more than a few LOC. 
But that aside, how would you implement cancellation/termination? simply closing the socket from outside the loop?

**Comment by garyburd** [comment]
There's not a one size fits all goroutine. The API will need to expose a number of options.  The code to set an option may not be significantly shorter than just writing the code.  An example is the option for handling backfill. Because there are many ways to fetch the backfill, this option is probably specified with a function.  Writing the backfill inline in the goroutine is the same size or smaller than writing a function literal to do it. Writing the code inline is easier to understand.

I have used the subscription count to terminate the loop as in [this example](http://godoc.org/github.com/garyburd/redigo/redis#example-PubSubConn).

**Comment by garyburd** [comment]
This feature can be added in another package. I am not adding significant new features to Redigo.
