### ISSUE TITLE
binding golang's context to pool and connection

### ISSUE THREAD

**Issue by hsinhoyeh** [garyburd/redigo#129]
We have a proposal which wants to bind a golang context into redigo's connection.
so the usage will be more like this

```
diff --git a/github.com/garyburd/redigo/redis/conn.go b/github.com/garyburd/redigo/redis/conn.go
index ac0e971..6dcf25e 100644
--- a/github.com/garyburd/redigo/redis/conn.go
+++ b/github.com/garyburd/redigo/redis/conn.go
@@ -354,7 +354,28 @@ func (c *conn) readReply() (interface{}, error) {
        return nil, protocolError("unexpected response line")
 }

-func (c *conn) Send(cmd string, args ...interface{}) error {
+func (c *conn) Send(ctx context.Context, cmd string, args ...interface{}) error {
+       // check context status
+       select {
+       case <-ctx.Done():
+               return ErrCanceled
+       default:
+       }
+
+       nilOrErrChan := make(chan error, 1)
+       go func(ch chan error) {
+               ch <- c.send(cmd, args)
+       }(nilOrErrChan)
+
+       // wait for done or canceled
+       select {
+       case <-ctx.Done():
+               return ErrCanceled
+       case err := <-nilOrErrChan:
+               return err
+       }
+}
+
+func (c *conn) send(cmd string, args ...interface{}) error {
```

pros:
1. leave caller more freedom to determine the timeout issue via context.Context
right now, the read/write timeout is controlled in DialTimeout https://github.com/garyburd/redigo/blob/master/redis/conn.go#L62
, which should be determined during the setup phase. It actually forbidden caller to cancel on demand.

cons:
1. every commands will bind a context, I don't like it.
so we can pass context.Context when we try to get a conn from a pool.
```
diff --git a/github.com/garyburd/redigo/redis/pool.go b/github.com/garyburd/redigo/redis/pool.go
index 9daf2e3..4d45537 100644
--- a/github.com/garyburd/redigo/redis/pool.go
+++ b/github.com/garyburd/redigo/redis/pool.go
@@ -147,7 +147,11 @@ func NewPool(newFn func() (Conn, error), maxIdle int) *Pool {
 // getting an underlying connection, then the connection Err, Do, Send, Flush
 // and Receive methods return that error.
 func (p *Pool) Get() Conn {
-       c, err := p.get()
+       return p.GetWithContext(nil)
+}
+
+func (p *Pool) GetWithContext(ctx context.Context) Conn{
+       c, err := p.get(ctx)
        if err != nil {
                return errorConnection{err}
        }
```

any comments?

**Comment by garyburd** [comment]
This design is difficult to use correctly. Consider what happens when `Send` returns before the underlying call to `send` completes:

- A second call to `Send` may result in a concurrent call to `send`.  Concurrent calls are [not supported](http://godoc.org/github.com/garyburd/redigo/redis#hdr-Concurrency).
- The application cannot determine if `send` completed successfully and therefore cannot know if the application should receive a response or not.

**Comment by hsinhoyeh** [comment]
yap, you are right. how about we have to follow the following protocols:
1. once commands are send to redis, the operation cannot be canceled.
 - so there won't be a case of concurrent calls.
2. once we cancel an operation, we need to clean up the env, like writebuffer https://github.com/garyburd/redigo/blob/master/redis/conn.go#L44
 - it is better to drop the conn, but the cost will be higher.

for read part is much more trivial.

**Comment by garyburd** [comment]
The purpose of the timeouts specified in DialTimeout is to detect a dead or stuck server.  They are not intended to be used for application timeouts.

> . once commands are send to redis, the operation cannot be canceled. 

Because serializing the command arguments to the network is so fast, I don't seen the value in canceling an operation before the command is sent.

> for read part is much more trivial.

Canceling when a response is partially read is not trivial.
