### ISSUE TITLE
pooledConnection.Close is not thread safe

### ISSUE THREAD

**Issue by kgdev** [garyburd/redigo#178]
In golang, net.Conn.Close should always be thread safe.

conn.Close is thread safe which is good. However pooledConnection.Close is not. This cause "hang ups" in my application. We should fix it or document it clearly?

**Comment by garyburd** [comment]
> In golang, net.Conn.Close should always be thread safe.

Redigo connections do not satisfy the net.Conn interface.

> We should fix it or document it clearly?

The redis.Conn documentation should be updated to state that Close is not necessarily thread safe.  The redis.Pool documentation should be updated to state that Close is not thread safe.

**Comment by stevenh** [comment]
This caught me out with some tests where I wanted to close a connection to exercise the error handling of our code and was surprised to find that Close deadlocked causing me quite a few hours of debugging to confirm it was Close doing unexpected reads and writes :(

**Comment by garyburd** [comment]
An application can prevent Close from reading and writing by issuing commands to clear server modes for the connection.  

It may be safer for the pool to drop connections in a mode than it is to clear it.

**Comment by stevenh** [comment]
Unfortunately that wouldn't help in our case as the test in question was to recover from a broken PubSub connection, where the handler exits when no subscriptions exist; so the subscription must be present when the connection is closed, hence the server modes can't be cleared.

If there was a way to drop / hard close the connection that would work fine e.g. an Conn.Abort().

That said I'm not sure I would ever expect Close() to do any connection cleanup unless explicitly documented, so removing the cleanup in func (pc *pooledConnection) Close() may well be better.

What do you think?

**Comment by garyburd** [comment]
Please describe your scenario in more detail.

**Comment by stevenh** [comment]
Here's a quick sample which should give the gist:
https://play.golang.org/p/-6QeUQsBwf

In order to exercise the code in Run: "case error" we close psc.

The expected behavior is the connection is closed and the error case it triggered, however as the pooled connection tries to clean down the subscriptions which involves writing and then reading from the Conn which is results in two threads doing r/w ops the same Conn we get a hang.

Obviously this is a simple example so the code in error case is not worth testing.

You can frig the desired behavior in this case by removing the Sleep which will usually result in the close happening before the Receive is run but it can fail depending on timing.

Does that help clarify?

**Comment by garyburd** [comment]
If I understand correctly, you want to start a goroutine that reconnects and resubscribes on error.  You also need a way to stop that goroutine.  Is that correct?

**Comment by stevenh** [comment]
Correct with the addition that I need a way to force an error, which is what I was trying to use Close on the connection (simulating the server connection dropping).

**Comment by garyburd** [comment]
@stevenh OK, I understand now.  You should not rely on Close() closing the underlying network connection.  Adding the Abort() method to the Conn interface is a breaking change. See http://play.golang.org/p/J630i1WA4s for one way to force an error on the pooled connection.

**Comment by stevenh** [comment]
Sending QUIT on the psc works just fine, thanks for the tip :+1:
