### ISSUE TITLE
would it be possible to add a Pool interface?

### ISSUE THREAD

**Issue by robsix** [garyburd/redigo#231]
When unit testing my code, my redis based stores require a `*redis.Pool` but since this is a struct and not an interface it means it cant be mocked, so I currently maintain my own Pool interface in my lib:

```
type Pool interface{
    Get() redis.Conn
    ActiveCount() int
    Close() error
}
```

so now I can easily unit test my code since it depends on this interface and mocking it out is trivial, I just hoped the redis lib could have the interface added to it so it can always be matching with the implementation, rather than me having to keep my own version up-to-date. If this isn't an appropriate request for the lib, no worries, thanks, for your consideration.

**Comment by garyburd** [comment]
There's no advantage to adding the interface type to Redigo.  Because I will not make an incompatible change to the API, the interface definition in your application will always be up-to-date. 

In the hypothetical scenario where I do make an incompatible change to the pool API, you will need to update code that uses the pool type. It will be easy to update your local interface definition at the same time.

A disadvantage of adding the proposed type is that it has more methods than what most applications need for testing. Many applications can work with:

     type pool func() redis.Conn

**Comment by robsix** [comment]
true, thanks.
