### ISSUE TITLE
hmget

### ISSUE THREAD

**Issue by fbbin** [garyburd/redigo#243]
Ask questions at https://stackoverflow.com/questions/ask?tags=go+redis
when I use 
`s1 := []string{"name", "level"}
	value, err := redis.Strings(pool.Get().Do("hmget", "user:level:info", s1[0], s1[1]))`,then it works ok, but when I change like this 
`s1 := []string{"name", "level"}
	value, err := redis.Strings(pool.Get().Do("hmget", "user:slevel:250", s1...))`
then thow an error:
` too many arguments in call to pool.Get().Do`
Why???😂

**Comment by GlenDC** [comment]
This is more of a `Golang` issue, rather than a `redigo` specific question. Feel free to ask such a question in the gopher slack chat. They love such questions, you can get an invite for it @ https://invite.slack.golangbridge.org

In the meanwhile I'll answer your question here:

The reason why it doesn't work is because the type signature of the `Do` method is:

```go
Do(commandName string, args ...interface{}) (reply interface{}, err error)
```

while what you are trying to do in the second example you give, would require a method with the following signature:

```go
Do(commandName string, key string, args ...interface{}) (reply interface{}, err error)
```

Your second example would work if you would modify your code to the following:

```go
s1 := []string{"user:slevel:250", "name", "level"}
value, err := redis.Strings(pool.Get().Do("hmget", s1...))
```

When you use the `...` operator (see: https://blog.golang.org/go-slices-usage-and-internals), to expand an array into a function which has a [variadic](https://en.wikipedia.org/wiki/Variadic_function) argument, it fills in every possible spot of that argument, and thus you cannot first give a single argument, and than an expanded list, as that would be all possible spots + 1 extra. Don't ask me why it is not possible, but Golang doesn't allow it.

**Comment by garyburd** [comment]
@GlenDC Thank you for answering this.
